"""Deterministic, non-authoritative Markdown projection of a V2 Plan."""

from __future__ import annotations

import html

from .domain import Plan


def _plain(value: str) -> str:
    """Make model-produced text inert while retaining it as readable text.

    Newlines and carriage returns are shown explicitly so a value cannot alter
    the document structure and the generated document always uses LF endings.
    """

    escaped = html.escape(value, quote=False)
    escaped = escaped.replace("\\", "\\\\").replace("\r", "\\r").replace("\n", "\\n")
    for character in "`*_[]()#+-!|>":
        escaped = escaped.replace(character, f"\\{character}")
    return escaped


def _inline_code(value: str) -> str:
    return "`" + value.replace("`", "\\`").replace("\r", "\\r").replace("\n", "\\n") + "`"


def _list(values: tuple[str, ...], *, code: bool = False) -> list[str]:
    if not values:
        return ["None."]
    format_value = _inline_code if code else _plain
    return [f"- {format_value(value)}" for value in values]


def render_plan_markdown(plan: Plan) -> str:
    """Render *plan* as a stable human review view with exactly one final LF."""

    lines = [
        "# Plan",
        "",
        "> Human-readable projection generated from the canonical `002-plan.json`.",
        "> Do not edit this file as an approval source.",
        "",
        "## Revision",
        "",
        str(plan.revision),
        "",
        "## Strategy",
        "",
        _plain(plan.strategy),
        "",
        "## Assumptions",
        "",
        *_list(plan.assumptions),
        "",
        "## Verification Strategy",
        "",
        *_list(plan.verification_strategy),
        "",
        "## Tasks",
    ]
    for task in plan.tasks:
        lines.extend([
            "",
            f"### {_plain(task.id)} — {_plain(task.objective)}",
            "",
            f"**Complexity:** {_plain(task.complexity)}  ",
            f"**Risk:** {_plain(task.risk)}",
            "",
            "#### Dependencies",
            "",
            *_list(task.depends_on, code=True),
            "",
            "#### Relevant Files",
            "",
            *_list(task.relevant_files, code=True),
            "",
            "#### Existing Patterns",
            "",
            *_list(task.existing_patterns),
            "",
            "#### Requirements",
            "",
            *_list(task.requirements),
            "",
            "#### Acceptance Criteria",
            "",
            *_list(task.acceptance_criteria),
            "",
            "#### Verification",
            "",
            *_list(task.verification),
            "",
            "#### Constraints",
            "",
            *_list(task.constraints),
        ])
    return "\n".join(lines) + "\n"
